### ISSUE TITLE
Incompatible

### ISSUE THREAD

**Issue by ManuelW77** [xyzaxyz/OctoPrint-Finetunerptr#3]
Hey there,

on OctoPrint 1.3.2 i can't install this Plugin. The button is greyed out with "incompatible".

**Comment by xyzaxyz** [comment]
Hi,
thanks for that hint! I accidently made a mistake in the compatibility section for the plugin. I already started a new pull request, so that the plugin will soon be installable from the plugin manager.
Until then, you will have to install it manually via: https://github.com/xyzaxyz/OctoPrint-Finetunerptr/archive/master.zip
Happy printing!

**Comment by xyzaxyz** [comment]
It should now be compatible and installable, I tested the case as the plugin repository got updated this morning.
So, this here will be closed :)
